= Apache Causeway Petclinic example with custom Vaadin UI

This repository contains an example based on the  link:https://causeway.apache.org[Apache Causeway] PetClinic tutorial. In this version we continue from the last step of the tutorial and add a customized Vaadin UI to it, where customers of the PetClinic could check their appointment times without logging in to the system.

== Running the app

Requirements:

* Java 17 LTS (eg link:https://adoptopenjdk.net/[Adopt OpenJDK] distribution)
* A fresh Maven (http://maven.apache.org/download.cgi[download])

Download the source as zip or checkout with git.

Build using Maven:

[source,bash]
----
mvn clean install
----


Run using Maven (or check out to your IDE and run via main class (PetClinicApp) :

[source,bash]
----
mvn -pl webapp spring-boot:run
----

Browse to http://localhost:8080.

The Vaadin UI is linked from the index page.

If you want to login to the "admin side" generated by Causeway:
Login using:

* either the secman superuser:

** username: `secman-admin`
** password: `pass`

* or as a regular user:

** username: `sven`
** password: `pass`

